<?xml version="1.0" encoding="utf-8"?><Database Name="CrestAccountingDatabase" Class="CTADataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\CrestAccountingDatabase.mdf;Integrated Security=True" SettingsObjectName="CrestAccountingSystem.Properties.Settings" SettingsPropertyName="AccountingDataBaseConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccountNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccountContactName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Account_CATransaction" Member="CATransactions" ThisKey="AccountNumber" OtherKey="AccountNumber" Type="CATransaction" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Employee_AssetInventory" Member="AssetInventories" ThisKey="EmployeeId" OtherKey="Owner" Type="AssetInventory" />
    </Type>
  </Table>
  <Table Name="dbo.CATransaction" Member="CATransactions">
    <Type Name="CATransaction">
      <Column Name="TransactionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Credit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Debit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Desciption" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AccountNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_CATransaction" Member="Account" ThisKey="AccountNumber" OtherKey="AccountNumber" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AssetInventory" Member="AssetInventories">
    <Type Name="AssetInventory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Employee_AssetInventory" Member="Employee" ThisKey="Owner" OtherKey="EmployeeId" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>